export const FETCH_CUSTOMERDETAILS_REQUEST = "FETCH_CUSTOMERDETAILS_REQUEST";
export const FETCH_CUSTOMERDETAILS_SUCCESS = "FETCH_CUSTOMERDETAILS_SUCCESS";
export const FETCH_CUSTOMERDETAILS_FAILURE = "FETCH_CUSTOMERDETAILS_FAILURE";