export const FETCH_UPCOMINGCUSTOMERDETAILS_REQUEST =
  "FETCH_UPCOMINGCUSTOMERDETAILS_REQUEST";
export const FETCH_UPCOMINGCUSTOMERDETAILS_SUCCESS =
  "FETCH_UPCOMINGCUSTOMERDETAILS_SUCCESS";
export const FETCH_UPCOMINGCUSTOMERDETAILS_FAILURE =
  "FETCH_UPCOMINGCUSTOMERDETAILS_FAILURE";