export const FETCH_GLOBAL_REQUEST = "FETCH_GLOBAL_REQUEST";
export const FETCH_GLOBAL_SUCCESS = "FETCH_GLOBAL_SUCCESS";
export const FETCH_GLOBAL_FAILURE = "FETCH_GLOBAL_FAILURE";
export const GOTO_NEXT_PAGE = "GOTO_NEXT_PAGE";
export const GOTO_PREV_PAGE = "GOTO_PREV_PAGE";
